services:
  app:
    build:
      context: ./docker/php
      args:
        user: ${USER}
        uid: ${UID}
        #uid: 1000
    container_name: laravel-app
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    working_dir: /var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: laravel-web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge